# Generated by Django 2.2.6 on 2019-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='availability',
        ),
        migrations.AlterField(
            model_name='venue',
            name='room_no',
            field=models.CharField(default='10', max_length=10, null=True),
        ),
    ]
