# Generated by Django 2.2.6 on 2019-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191025_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='building_name',
            field=models.CharField(default='IRIS labs', max_length=50, null=True),
        ),
    ]
