# Generated by Django 2.2.6 on 2019-10-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191025_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managing',
        ),
        migrations.DeleteModel(
            name='Managing_Team',
        ),
    ]
