# Generated by Django 2.2.6 on 2019-10-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191025_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Where',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Venue')),
            ],
        ),
    ]
