# Generated by Django 2.2.6 on 2019-10-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20191027_1303'),
        ('event', '0008_auto_20191027_1302'),
    ]

    operations = [
    ]
