# Generated by Django 2.2.6 on 2019-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20191028_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
